pool:
  vmImage: ubuntu-16.04

container: debian:stable-slim

jobs:

  - job: say_hello
    timeoutInMinutes: 3
    steps:
      - script: echo "hello world"

    
  - job: say_goodbye
    timeoutInMinutes: 3
    steps:
      - script: echo "goodbye crual world"