resources:
  containers:
    - container: deb
      #image: samueldebruyn/debian-git
      image: debian:stable-slim

pool:
  vmImage: ubuntu-16.04

jobs:

  - job: create_file
    container: deb
    timeoutInMinutes: 5
    steps:
      - checkout: self
        persistCredentials: true
      - bash: |
          echo "creating a file..."
          touch $(head -3 /dev/urandom | tr -cd '[:alnum:]' | cut -c -8).txt

  - job: commit_file
    dependsOn: create_file
    timeoutInMinutes: 3
    steps:
      - checkout: self
        persistCredentials: true
      - bash: |
          git config --global user.email "wjconnor123@gmail.com"
          git config --global user.name "William Connor"
          git status
          git add . && git commit -m "added a file [skip ci]"
          git push origin HEAD:master
