resources:
  containers:
    - container: deb
      image: samueldebruyn/debian-git
      #image: debian:stable-slim

pool:
  vmImage: ubuntu-16.04

jobs:

  - job: say_hello
    container: deb
    timeoutInMinutes: 3
    steps:
      - checkout: self
        persistCredentials: true
      - bash: |
          git config --global user.email "wjconnor123@gmail.com"
          git config --global user.name "William Connor"
          git status
          echo "creating a file..."
          touch foo.txt
          git add . && git commit -m "added a file [skip ci]"
