pool:
  vmImage: ubuntu-16.04

jobs:

  - job: say_hello
    container: debian:stable-slim
    timeoutInMinutes: 3
    steps:
      - script: echo "hello world"

    
  - job: say_goodbye
    container: debian:stable-slim
    timeoutInMinutes: 3
    steps:
      - script: echo "goodbye crual world"