data: ./data

environments:


  # these are the main envs to be versioned

  enbw.dev:
    baseUrl: https://enbw.dev.babelforce.com
    auth:
      accessId: 912e699b-c019-45e5-a28b-ae38e63dfe25
      accessToken: 5c2230c36a4f4222a2cbcf15e494197e

  enbw.staging:
    baseUrl: https://enbw.staging.babelforce.com
    auth:
      accessId: 12ed0b65-589f-43d8-b360-083114336b3e
      accessToken: 1853397109ec4960ad131a270a61c3a0


  ## this clone env is used to revert an env state to a previous version.
  ## it is not versioned, so can be used to represent the current
  ## state of IVRs for use in `diff` and `apply` tasks

  enbw.dev__temp:
    baseUrl: https://enbw.dev.babelforce.com
    auth:
      accessId: 912e699b-c019-45e5-a28b-ae38e63dfe25
      accessToken: 5c2230c36a4f4222a2cbcf15e494197e


synchronize:


  # target is versioned, source is current state
  enbw.dev-revert:
    from: enbw.dev
    to: enbw.dev__temp

  # standard deploy task
  enbw.dev-to-enbw.staging:
    from: enbw.dev
    to: enbw.staging
